# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/psql-front
    binary: psql-front
    ldflags:
      - -s -w
      - -X main.Version=v{{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64
release:
  prerelease: true
archives:
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Env.NIGHTLY_VERSION }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
